// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TacticalBoard.Infrastructure.Persistence;

#nullable disable

namespace TacticalBoard.Api.Persistence.Migrations
{
    [DbContext(typeof(TacticalBoardDbContext))]
    [Migration("20261004170158_AddTeams")]
    partial class AddTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TacticalBoard.Folders.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area_kind");

                    b.Property<Guid>("AreaOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("AreaKind", "AreaOwnerId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_area_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.Situation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area_kind");

                    b.Property<Guid>("AreaOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("current_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field_type");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("format_version");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sport");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_situations");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_situations_folder")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("AreaKind", "AreaOwnerId", "NormalizedTitle")
                        .IsUnique()
                        .HasDatabaseName("ix_situations_area_title")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("situations", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.SituationRevision", b =>
                {
                    b.Property<Guid>("SituationId")
                        .HasColumnType("uuid")
                        .HasColumnName("situation_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.HasKey("SituationId", "Number")
                        .HasName("pk_situation_revisions");

                    b.ToTable("situation_revisions", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Teams.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LogoHash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("logo_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_code");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Teams.Domain.TeamLogo", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("TeamId")
                        .HasName("pk_team_logos");

                    b.ToTable("team_logos", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Teams.Domain.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_team_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_memberships_user")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_memberships_team_user")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayNameValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsSystemAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_administrator");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<string>("PreferredLanguageValue")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_issuer_subject")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.SituationRevision", b =>
                {
                    b.HasOne("TacticalBoard.Situations.Domain.Situation", null)
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_situation_revisions_situations_situation_id");
                });

            modelBuilder.Entity("TacticalBoard.Teams.Domain.TeamLogo", b =>
                {
                    b.HasOne("TacticalBoard.Teams.Domain.Team", null)
                        .WithOne()
                        .HasForeignKey("TacticalBoard.Teams.Domain.TeamLogo", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_logos_teams_team_id");
                });

            modelBuilder.Entity("TacticalBoard.Teams.Domain.TeamMembership", b =>
                {
                    b.HasOne("TacticalBoard.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_teams_team_id");
                });
#pragma warning restore 612, 618
        }
    }
}
