// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TacticalBoard.Infrastructure.Persistence;

#nullable disable

namespace TacticalBoard.Api.Persistence.Migrations
{
    [DbContext(typeof(TacticalBoardDbContext))]
    partial class TacticalBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TacticalBoard.Folders.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area_kind");

                    b.Property<Guid>("AreaOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("AreaKind", "AreaOwnerId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_area_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.Situation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area_kind");

                    b.Property<Guid>("AreaOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("current_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field_type");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("format_version");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sport");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_situations");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_situations_folder")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("AreaKind", "AreaOwnerId", "NormalizedTitle")
                        .IsUnique()
                        .HasDatabaseName("ix_situations_area_title")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("situations", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.SituationRevision", b =>
                {
                    b.Property<Guid>("SituationId")
                        .HasColumnType("uuid")
                        .HasColumnName("situation_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.HasKey("SituationId", "Number")
                        .HasName("pk_situation_revisions");

                    b.ToTable("situation_revisions", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayNameValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsSystemAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_administrator");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_issuer_subject")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TacticalBoard.Situations.Domain.SituationRevision", b =>
                {
                    b.HasOne("TacticalBoard.Situations.Domain.Situation", null)
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_situation_revisions_situations_situation_id");
                });
#pragma warning restore 612, 618
        }
    }
}
