using System.Diagnostics.CodeAnalysis;

namespace TacticalBoard.Teams.Domain;

/// <summary>
/// A team's identifier code (arc42 ch. 1, 8.17): exactly <see cref="Length"/> characters from
/// <see cref="Alphabet"/> (A–Z, 0–9), generated by the system when the team is created and never
/// changed. The team's link (<c>/teams/&lt;CODE&gt;</c>) contains it. Parsing accepts lower case
/// (a typed link) and surrounding whitespace.
/// </summary>
internal sealed record TeamCode
{
    /// <summary>The number of characters of a code.</summary>
    public const int Length = 6;

    /// <summary>The characters a code is made of: upper-case letters and digits.</summary>
    public const string Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    private TeamCode(string value) => Value = value;

    /// <summary>The code, upper case.</summary>
    public string Value { get; }

    /// <summary>Reads a code; <c>false</c> unless it has exactly six letters or digits (A–Z, 0–9, any case).</summary>
    public static bool TryParse(string? text, [NotNullWhen(true)] out TeamCode? code)
    {
        var candidate = text?.Trim().ToUpperInvariant() ?? string.Empty;
        code = candidate.Length == Length && candidate.All(character => Alphabet.Contains(character, StringComparison.Ordinal))
            ? new TeamCode(candidate)
            : null;
        return code is not null;
    }

    /// <summary>Reads a code that must be valid.</summary>
    /// <exception cref="ArgumentException">It isn't a valid code.</exception>
    public static TeamCode Parse(string text) =>
        TryParse(text, out var code) ? code : throw new ArgumentException($"'{text}' is not a team code.", nameof(text));

    /// <inheritdoc />
    public override string ToString() => Value;
}
